### ISSUE TITLE
Un-entry-point plugin for manual registration

### ISSUE THREAD

**Issue by ebolyen** [qiime2/q2-mystery-stew#9]
This plugin should probably be registered by an interface's test-suite manually (and entry-point removed). There is an API for this, so we just need to create a public-facing factory which will generate a plugin object which can be registered. See this [comment](https://github.com/qiime2/q2-mystery-stew/issues/4#issuecomment-714636912) for additional motivation.

**Comment by Oddant1** [comment]
I forgot to put "closes #9" in #10
